# Generated by Django 2.2.3 on 2020-05-15 16:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Educator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('middle_name', models.CharField(default='default', max_length=100)),
                ('departament', models.CharField(max_length=100)),
                ('position', models.CharField(max_length=100)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Timetable',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('group', models.CharField(max_length=100)),
                ('start', models.CharField(blank=True, default='2020-03-02T09:30:00', max_length=25)),
                ('end', models.CharField(blank=True, default='2020-03-03T09:30:00', max_length=25)),
                ('subject', models.CharField(max_length=500)),
                ('educator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Educator')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('middle_name', models.CharField(default='default', max_length=100)),
                ('group', models.CharField(max_length=100)),
                ('entry_year', models.IntegerField()),
                ('graduate_year', models.IntegerField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attended', models.BooleanField()),
                ('emotion', models.CharField(blank=True, max_length=20)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Student')),
                ('timetable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Timetable')),
            ],
        ),
    ]
