# Generated by Django 2.2.3 on 2020-05-16 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='degree',
            field=models.CharField(choices=[('UG', 'undergraduate'), ('G', 'graduate')], default='undergraduate', max_length=20),
        ),
        migrations.AddField(
            model_name='student',
            name='study_form',
            field=models.CharField(choices=[('FT', 'full-time'), ('PT', 'part-time')], default='full-time', max_length=20),
        ),
    ]
