# Generated by Django 2.2.3 on 2020-04-26 22:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_customuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
