# Generated by Django 2.2.3 on 2020-05-16 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20200516_1530'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='degree',
            field=models.CharField(choices=[('UG', 'Студент Бакалавриата'), ('G', 'Магистрант')], default='UG', max_length=20),
        ),
        migrations.AlterField(
            model_name='student',
            name='study_form',
            field=models.CharField(choices=[('FT', 'Очная форма обучения'), ('PT', 'Заочная форма обучения')], default='FT', max_length=20),
        ),
    ]
