# Generated by Django 2.2.3 on 2020-04-26 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_delete_customuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='educator',
            name='middle_name',
            field=models.CharField(default='default', max_length=100),
        ),
        migrations.AddField(
            model_name='student',
            name='middle_name',
            field=models.CharField(default='default', max_length=100),
        ),
    ]
