# Generated by Django 2.2.3 on 2020-04-26 22:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20200427_0320'),
    ]

    operations = [
        migrations.CreateModel(
            name='EducatorAndSubject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('educator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Educator')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Group')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Subject')),
            ],
        ),
    ]
